# Generated by Django 5.2.18 on 2026-10-07 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='upload_at',
            new_name='updated_at',
        ),
    ]
